#!/usr/bin/env bash

TOKENFILE=".session-token.txt"

if [[ -n $DEBUG ]]; then
    set -x
fi

main(){
    local value
    trap handle-exit EXIT 

    case "$1" in 
        self-test) self-test
            ;;
        refresh)
            value="$(./fetch-session-token)"
            persist "$value"
            ;;
        delete) delete;
            ;;
        persist) 
            shift
            persist "$@"
            ;;
        invalidate) 
            invalidate-old
            ;;
        export) do-export
            ;;
        *) 
            usage 
            exit 1
            ;;
    esac
}

# no-op, exit in tests, where it is overwritten for teardown
handle-exit(){
    :
}

delete-tokenfile(){
    rm -f "$TOKENFILE"
}

persist(){
    if [ -z "$1" ]; then
        error "Nothing to persist. No argument received"
    fi
    echo "$@" > "$TOKENFILE"
}

# exit status:
# 1 if invalid or invalid
invalidate-old(){
    # invalidate any cookie older than six hours
    if  [[ $(find . -mtime -6h -name "$TOKENFILE" -print -quit) == '' ]]; then
        delete-tokenfile
        return 1
    fi
}

do-export(){
    local session
    if [[ ! -e "$TOKENFILE" ]]; then
        error "No cookie stored."
    fi
    session=$(cat "$TOKENFILE")
    echo "export INATUR_COOKIE='session=$session; aktivTilbyder=$INATUR_AKTIVTILBYDER'"
}

error(){
        echo "$@" >&2
        exit 1
}

self-test(){
    assert(){
        if [[ $# != 2 ]]; then 
            echo "assert() requires 2 args: <test> <msg>"
            exit 1
        fi
        if ! eval "$1"; then 
            shift
            echo "$@"
            exit 1
        fi
    }
    test_invalidate(){
        rm -f "$TOKENFILE"
        assert '! invalidate-old' 'Expected to fail on missing tokenfile'

        touch "$TOKENFILE"
        assert 'invalidate-old'   'Expected not to fail on new tokenfile'
    }

    handle-exit(){
        echo "test teardown"
        delete-tokenfile
    }
    test_invalidate
}

usage(){
    echo
    echo "USAGE: $0 <option> [argument]"
    echo "  where <option> is one of "
    echo '
    export              Prints the INATUR_COOKIE as an export statement for "eval" 
    invalidate          OK if < 6h old cookie, else exit status of 1
    persist <cookie>    Will persist the session cookie
    delete              Force delete. Typical on a 401
    refresh             refresh the session cookie
    self-test           Run built-in tests
    '
}

main "$@"
